baseURL = "https://diefish1024.github.io/"
languageCode = "zh-cn"
title = "diefish's blog"
theme = "PaperMod"
preserveTaxonomyNames = true

enableRobotsTXT = true
enableEmoji = true
buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 5

[minify]
  disableXML = true
  minifyOutput = true

[params]
  math = true

  env = "production"
  title = "diefish's blog"
  description = "A freshman at SJTU John class."
  author = "diefish"
  images = ["/images/avatar.jpg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.comments]
  enabled = true
  provider = "giscus"

  [params.assets]
    favicon = "/images/avatar.jpg"
    favicon16x16 = "/images/avatar.jpg"
    favicon32x32 = "/images/avatar.jpg"
    apple_touch_icon = "/images/avatar.jpg"
    safari_pinned_tab = "/images/avatar.jpg"

  [params.label]
    text = "Home"
    icon = "/images/avatar.jpg"
    iconHeight = 35

  [params.profileMode]
    enabled = true
    title = "diefish"
    subtitle = "A freshman at SJTU John class."
    imageUrl = "/images/avatar.jpg"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "diefish's image"
    buttons = [
      { name = "Posts", url = "posts" },
      { name = "Tags", url = "tags" },
      { name = "Search", url = "search" }
    ]

  [params.cover]
    hidden = true
    hiddenInList = true
    hiddenInSingle = true

  [params.editPost]
    URL = "https://github.com/diefish1024/diefish1024.github.io/blob/main/content"
    Text = "Suggest Changes"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/diefish1024"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "search"
    url = "search"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[outputs]
  home = [
    "HTML",
    "RSS",
    "JSON"
  ]
